### Create Product
POST http://localhost:5000/api/product

{
  "product_name":"Komputer",
	"purchase_price":3500000,
	"selling_price":5000000,
	"stock":40
}

### Find Product
GET http://localhost:5000/api/product?page=1&limit=3&search=

### Get Product
GET http://localhost:5000/api/product/ad588905-9060-4ab6-a414-758c96e72b64

### Update Product
PUT http://localhost:5000/api/product/6e003967-aece-444a-9caa-6397981293a4

{
	"product_name":"Komputer",
	"purchase_price":0,
	"selling_price":5000000,
	"stock":0
}

### Delete Product
DELETE http://localhost:5000/api/product/41ea634a-30e5-4700-8ece-3030af4a72c7

### Create Transaction
POST http://localhost:5000/api/transaction

{
	"products":[
		{
			"product_id":"ad588905-9060-4ab6-a414-758c96e72b64",
			"amount":2
		},
		{
			"product_id":"de0c7c2c-5108-46ed-a3bf-a22f66cff829",
			"amount":2
		}
	]
}

### Find Transaction
GET http://localhost:5000/api/transaction?startDate=2023-09-21&endDate=2023-09-30&page=1&limit=10

### Get Transaction
GET http://localhost:5000/api/transaction/81bada9a-4eef-4fa5-b1f9-d5fa825f42a5

### Report Transaction
GET http://localhost:5000/api/transaction/report?startDate=2023-09-01&endDate=2023-09-30