### Create Product
POST http://localhost:5000/api/product

{
  "product_name":"Kulkas",
	"purchase_price":700000,
	"selling_price":1000000,
	"stock":40
}

### Find Product
GET http://localhost:5000/api/product?page=1&limit=3&search=p

### Update Product
PUT http://localhost:5000/api/product/coba